Remove Promoted Tweets
sindresorhus/refined-twitter pull request #15
Opened 2017-12-08 11:04 UTC by Elyager

I added the code to remove promoted tweets, I hope is correct at least is working for me 😄

The second open source project that I do a small contribution, so let me know any corrections.

✌🏼

2017-12-08 18:35 UTC, sindresorhus requested changes

2017-12-08 18:35 UTC, sindresorhus commented on source/content.js
> +	$('#stream-items-id .promoted-tweet').remove();
You don't need `#stream-items-id`. The class is specific enough.

2017-12-08 18:35 UTC, sindresorhus commented on source/content.js
> +function cleanPromotedTweets() {
`cleanPromotedTweets` => `hidePromotedTweets`

2017-12-08 18:36 UTC, sindresorhus commented
Looking good! 👌😄

Can you add something like `- Hides promoted tweets` to https://github.com/sindresorhus/refined-twitter#highlights ?

2017-12-08 18:40 UTC, sindresorhus commented on source/content.js
> +	$('#stream-items-id .promoted-tweet').remove();
And you should probably remove the parent item, as that's the actual container, just to be safe. So:

```js
$('.promoted-tweet').parent().remove();
```

2017-12-16 00:09 UTC, sindresorhus commented
You also need to fix the merge conflict ;)

2017-12-16 00:25 UTC, Elyager commented
I finally got the time to get this quick fix done.

2017-12-16 00:32 UTC, sindresorhus approved these changes

2017-12-16 00:32 UTC, merged

2017-12-16 00:33 UTC, sindresorhus commented
Looks great. Thanks for contributing! :)