nav-button: add likes button to the navbar
sindresorhus/refined-twitter pull request #54
Opened 2018-02-08 17:35 UTC by vcapretz

when we want to access our liked tweets the current flow is:
click profile picture > profile > find likes button

with this new button you can click whenever you are at

<img width="674" alt="screen shot 2018-02-08 at 15 34 59" src="https://user-images.githubusercontent.com/14620121/35988497-ace9f93e-0ce5-11e8-8675-17e6ee38cd99.png">

2018-02-08 19:59 UTC, sindresorhus commented
The `Likes` button is added quite slowly. Many hundred milliseconds after the page has loaded.

And if I press the `Likes` button, it's added again. You need to check and prevent duplicate buttons. Example: https://github.com/sindresorhus/refined-github/blob/0d25d590e828fb54db2ad8342f8115aa4aa23ec8/source/features/add-gists-link-to-profile.js#L7-L11

2018-02-08 20:00 UTC, sindresorhus requested changes

2018-02-08 20:00 UTC, sindresorhus commented on source/content.js
> +		addLikeButtonNavbar();
Use `safely()` like the other calls above.

2018-02-08 20:00 UTC, sindresorhus commented on source/content.js
> +	`);
Use JSX. Example: https://github.com/sindresorhus/refined-twitter/blob/ae0bc9985fda2fd09f26b30915163c666e9eaf46/source/features/code-highlight.js#L64-L76

2018-02-08 20:00 UTC, sindresorhus commented on source/content.js
> +			<a role="button" data-nav="favorites" href="/i/likes" class="js-nav js-tooltip js-dynamic-tooltip" data-placement="bottom" data-original-title="">
I don't think you need to add `data-original-title=""`. It's added by the JS on hover.

2018-02-09 13:53 UTC, vcapretz commented
@sindresorhus thanks for the review! I just fixed them.

let me know if there's still something to be done 😁

2018-02-10 04:08 UTC, sindresorhus commented on source/features/likes-button-navbar.js
> +export default function () {
Use arrow function

2018-02-10 04:10 UTC, sindresorhus commented on source/features/likes-button-navbar.js
> +	if (globalActionsList.find('.refined-like-button').length > 0) {
`.refined-like-button` => `.refined-twitter_like-button`

2018-02-10 04:11 UTC, sindresorhus commented
It still loads pretty slowly. It's not a good experience when the button is visibly loaded after page load. @bfred-it Any tips for making it appear before the page is painted?

2018-02-10 07:31 UTC, bfred-it commented
Don’t wait for domready, use safeElementReady (this means you have to restore `run_at: document_start`)

2018-02-11 07:14 UTC, sindresorhus commented
@bfred-it Cool. I reverted your commit then: https://github.com/sindresorhus/refined-twitter/commit/fe35d0a98162a5c5aa7a0c6bedf5aa9d81192d01

2018-02-11 07:15 UTC, sindresorhus commented
@vcapretz Can you use `safeElementReady`? Example here: https://github.com/sindresorhus/refined-twitter/blob/fe35d0a98162a5c5aa7a0c6bedf5aa9d81192d01/source/content.js#L22

2018-02-11 07:16 UTC, sindresorhus commented
@vcapretz Can you also add this feature to the feature listing in the readme?

2018-02-11 07:20 UTC, fregante approved these changes

2018-02-11 15:59 UTC, filipekiss approved these changes

2018-02-11 23:23 UTC, vcapretz commented
sure @sindresorhus, I'll update it

2018-02-12 02:36 UTC, vcapretz commented
hey @sindresorhus I just applied the suggested changes! 

now the function runs on init, and I saw it has really improved the loading performance.

I also added the `safeElementReady` function to the main list were the new item is about to be added!

2018-02-12 05:32 UTC, sindresorhus approved these changes

2018-02-12 05:33 UTC, merged

2018-02-12 05:33 UTC, sindresorhus commented
Great. Thanks :)